### ISSUE TITLE
Attempt to yield across metamethod/C-call boundary caused by attempting to get _G.Aero in a client side module

### ISSUE THREAD

**Issue by Xuleos** [Sleitnick/AeroGameFramework#100]
I have a client-side module which is referenced pretty normally just
![image](https://user-images.githubusercontent.com/37721396/63633952-63f79800-c61e-11e9-8461-bd0baac8b886.png)
In that module, I'm trying to access the client framework global so that I can connect to a client event from a service.
![image](https://user-images.githubusercontent.com/37721396/63633987-b33dc880-c61e-11e9-8d95-fb6ec4424c5c.png)

Whenever that module is loaded, I get hit with this error.
![image](https://user-images.githubusercontent.com/37721396/63633991-c81a5c00-c61e-11e9-8b6e-3048266dcbf8.png)

I don't know if I'm just being an idiot as always or if this is a legitimate bug.

**Comment by Xuleos** [comment]
Forgot to add that this error gets thrown too 
![image](https://user-images.githubusercontent.com/37721396/63634049-365f1e80-c61f-11e9-83cc-1b3147d39b85.png)

**Comment by OverHash** [comment]
Hi there! I got this error as well, I noticed that it's a problem in any Module where you have something that yields in it. In my case, I had a module that looked something like this
![image](https://user-images.githubusercontent.com/46231745/63927156-46ed1a00-caa1-11e9-8d80-29db8b191951.png)

Since you can't yield in a metamethod, and AeroGameFramework requires all modules in __index, it errors.

https://github.com/Sleitnick/AeroGameFramework/blob/7b86222d66f6997096fa179b7c6739d1a91ca522/src/ServerScriptService/Aero/Internal/AeroServer.server.lua#L115

This section of code causes the issue.

It would be great for this to be fixed :)

**Comment by brinkokevin** [comment]
@OverHash You shouldn't yield there. This is how AeroGameFramework is loaded first all modules get required then Init function is called then Start is called. If you want to yield do it in the Start method.

**Comment by Sleitnick** [comment]
@brinkokevin is correct in both cases. Yielding should be avoided until you hit the `Init` method, but I highly recommend not yielding in `Init` either unless absolutely necessary. Ideally, don't yield until the `Start` method lifecycle.

When you yield within the `require` lifecycle stage, things get kinda funky.

@Xuleos, in your MoneyDisplay component, try writing a Start method on the module instead where you pick up the CurrencyService:

```lua
local CurrencyService

function MoneyDisplay:Start()
   CurrencyService = self.Services.CurrencyService
end
```

------------------------------

@OverHash, try moving the WaitForChild yield within Init or Start:

```
local npcFolder

...

function npcClass:Init()
   npcFolder = serverStorage:WaitForChild("NPCS")
end
```
