### ISSUE TITLE
UserInput.Keyboard ignoring gameproccesed for KeyUp

### ISSUE THREAD

**Issue by n00kii** [Sleitnick/AeroGameFramework#130]
here's whats in Keyboard
```lua
userInput.InputEnded:Connect(function(input, processed)
	if (input.UserInputType == Enum.UserInputType.Keyboard) then
		self.KeyUp:Fire(input.KeyCode)
	end
end)
```
i believe this can be fixed by
````lua
userInput.InputEnded:Connect(function(input, processed)
	if (processed) then return end
	if (input.UserInputType == Enum.UserInputType.Keyboard) then
		self.KeyUp:Fire(input.KeyCode)
	end
end)
```

**Comment by Sleitnick** [comment]
This was actually done intentionally to mimic the mouse module, which also does this. The justification behind the _mouse_ doing this is quite simple:

- Mouse down (not processed), so start a task (e.g. shoot a gun)
- Mouse up (not processed), stop the task(e.g. stop shooting)

_If_ the Mouse Up event was processed (e.g. the user let go of clicking while over a UI button), then the task wouldn't end and the user would continue shooting.

_However_, this is not very justifiable using the keyboard, since I can't think of a similar use-case. Therefore, yes, you are correct. I'll mark this as a bug and try to add it in soon.

Thanks!

**Comment by Sleitnick** [comment]
Completed in https://github.com/Sleitnick/AeroGameFramework/commit/634ece70c3bd45bcb991f4e5e9718177db6742d9
