### ISSUE TITLE
Remove the StoreService

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#149]
Developers should be responsible to create their own service for tracking purchases, and such a liability should not exist upon this framework.

**Comment by Darkshepherd** [comment]
I agree. It is one of the first things I did (I removed the store service). I also removed the data service because I already was using DataStore2. But, the one included in AGF might have been really good if I didn't already have a data service that I liked.

I liked the rest of the included utilities. Even if I haven't used them yet, I'm keeping them around for future use.

But yeah: the store just seemed like something each game would need to manage on its own.
