### ISSUE TITLE
Plugin should notify when an update is available

### ISSUE THREAD

**Issue by alexglatham** [Sleitnick/AeroGameFramework#2]
It would be nice if the plugin notified developers when an update to the source code is available so the framework can be updated.

**Comment by Sleitnick** [comment]
Hi alexglatham. This is a great idea! I will put this in my backlog.

**Comment by Sleitnick** [comment]
I am starting work on this later today after work. I cannot promise that this will be added. The tricky part is that this requires use of the HttpService, which by default is turned off. Trying to invoke HTTP requests with it off will result in an ugly error for the user. Last time I checked, even accessing the `HttpEnabled` property is restricted.

I think this feature _must_ be able to silently and automatically check for updates, otherwise it would not be of much use for developers, since updating it still will require going out and running the install script from the command line again (command line runs at higher security level than plugins).

Again, I think this feature request is great and I will try to see what I can do, but can't promise anything at the moment.

**Comment by Sleitnick** [comment]
The plugin has now been updated and will now notify the developer if the framework has any updates. It does this by tracking the `version.txt` file in the repository. A local copy of the version is stored when the framework is installed or updated.

When the user first clicks into the hierarchical viewport in Studio during a new session, it will show the user a message that an update is available. This message can be dismissed by the user. It will also automatically disappear after 30 seconds.

The user still must use the command line to install the framework again due to the permissions needed. Thus, the plugin cannot make the update on the user's behalf.
