### ISSUE TITLE
Event for when SafeDataStore fails

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#29]
Currently when SafeDataStore fails to do something, it just warns, and that pretty much it. A way to easily handle Data Store failures would be great.

**Comment by Sleitnick** [comment]
For those wondering, this references the SafeDataStore Try method:

```lua
function SafeDataStore:Try(method, k, v)
	local value = nil
	for i = 1,MAX_ATTEMPTS do
		local success,v = pcall(function()
			return self.DataStore[method](self.DataStore, k, v)
		end)
		if (success) then
			value = v
			break
		elseif (i == MAX_ATTEMPTS) then
			warn("DataStore " .. method .. " failed: " .. tostring(v))
		else
			wait(ATTEMPT_INTERVAL)
		end
	end
	return value
end
```

The current behavior is that it simply calls `warn()` if it reaches the maximum attempts. In other words, it is essentially failing silently. A warning is not sufficient. There should be some sort of communication to the server (and maybe client?) that this has failed. Probably through an event.

**Comment by Dog2puppy** [comment]
> There should be some sort of communication to the server (and maybe client?)

Maybe just send the event to whichever side invoked it?

**Comment by Sleitnick** [comment]
It can only be invoked server-side, but the DataService could be smart to pass along the event if it knows that the context involves a given player.

Another note to make: DataStoreService.AutomaticRetry is enabled by default (a new feature released after this framework was initially released). So by default, failed DataStore calls will retry without any code; however, it can still exhaust its retry limit and raise an error, thus still justifying a need for handling retries through custom code. It raises the question: Does this AutomaticRetry feature also change how this Try method should be structured overall?

Another noteworthy point: What happens if the Try method is executing on multiple same keys? It should probably have safe-guards against that too.

**Comment by Dog2puppy** [comment]
AutomaticRetry hasen't been enabled yet according to the post for it. And by passing the event to the side that invoked it, I meant which side invoked the methods exposed in the DataService. Server should probably get the event anyways.

**Comment by Sleitnick** [comment]
Yeah just saw that post. It's misleading because the Wiki and RobloxDev page document it normally.

**Comment by Dog2puppy** [comment]
Roblox's docs are messed up. Instead of doing stuff that's needed, we get a new robloxdev.com site. (Which is a nice improvement)

**Comment by Sleitnick** [comment]
I'll be adding the following events to the DataService:

Server:
- PlayerFailed(player, method, key)
- GlobalFailed(method, key)
- CustomFailed(name, scope, method, key)

Client:
- Failed(method, key)

Where 'method' is a string of the DataStore method (e.g. "SetAsync")

**Comment by Sleitnick** [comment]
Committed the change. I also passed the "errorMessage" to the events too. Since it's just a framework, it's up for the game developers to handle the events however they see fit. The framework won't try to do anything else.

**Comment by Dog2puppy** [comment]
Thanks! I’ll probably just give the player a GUI saying what keys didn’t work and give them the option to retry.

**Comment by Dog2puppy** [comment]
Also, I edited my comment on YouTube.
