### ISSUE TITLE
Mention that AeroServer and Areo are injected into modules

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/AeroGameFramework#31]
While looking at the recent DataService update to figure out how the event passing worked, I noticed that it was using `self.Shared.Event` which confused me because the README.md never mentions anything being injected into modules. Documentation on this would be very useful. (But it does only take a few minutes to reverse engineer AeroServer to the point where it gets injected)

**Comment by Sleitnick** [comment]
Yes, this was not always the case. Modules used to _not_ include injections. It was changed in later updates because it is quite useful to always have connection to the framework.

**Comment by Dog2puppy** [comment]
Is this from the `WrapModule` function? Or did it come earlier?

**Comment by Sleitnick** [comment]
I added `WrapModule` today because it seemed common (at least for me) to manually set metatables of my own custom modules to be included in the framework.

Before, lazy-loaded modules simply set the metatable when the modules were set up, but now I am utilizing the `WrapModule` method for those as well to keep things consistent.

**Comment by Sleitnick** [comment]
I have also started on overhauling the whole documentation too. So I will include this within that.

**Comment by Sleitnick** [comment]
This has been included within the new documentation. See the `ServerService.md` and `ClientController.md` files within the `doc` directory.
