### ISSUE TITLE
[Enhancement] Have installer remove deprecated items from the framework

### ISSUE THREAD

**Issue by Rocky28447** [Sleitnick/AeroGameFramework#49]
Pretty much what it says in the title. It would be nice if the installer would remove deprecated services and such from the game when the framework is updated (such as the PointsService).

**Comment by Sleitnick** [comment]
The challenge of this: It would have to explicitly identify that an existing module _used_ to be a part of the framework, but is no longer. This is challenging because it doesn't keep a history of the framework file list. Therefore it can't tell if a given file just doesn't exist anymore in the framework _or_ if the user simply created it themselves.

For instance, what if someone created their own PointsService module?

I'm curious if there are ways to go about this with the current structure.

**Comment by Rocky28447** [comment]
What about adding something to Filelist.json to signify that a module has been deprecated?

**Comment by Sleitnick** [comment]
For the time being, I don't want to mess with the overall structure of the filelist and thus also the installer. This might be something to revisit in the future, but I would consider it out of scope for now.
