### ISSUE TITLE
invalid key to 'next' in DataService

### ISSUE THREAD

**Issue by rafaskb** [Sleitnick/AeroGameFramework#73]
Hey, so I'm getting this error via analytics that doesn't happen too often, but its also not rare enough to be ignored. Here's the stacktrace:

```
invalid key to 'next'
    Stack Begin
    Script 'ServerStorage.Aero.Services.DataService', Line 204 - method FlushAll
    Script 'ServerStorage.Aero.Services.DataService', Line 256 - method AutoSaveLoop
    Script 'ServerStorage.Aero.Services.DataService', Line 339
    Stack End
```

**Comment by Sleitnick** [comment]
Interesting! I'll look into this later today. Thank you for the report!

Also as a side-note, the DataService will be retired in the near future. I'm building a much more robust data system, which is still in the testing phase.

**Comment by Sleitnick** [comment]
This has been fixed.

The problem was due to the synchronous nature of the auto-save step. If a player left during (or right before) an auto-save process, it's possible that the player's data cache would be removed. Removing items within a table while currently iterating through the table will cause all sorts of terrible things, such as the error you were seeing.

The following changes were made:

- The auto-save step now collects all the caches first before iterating through them in a separate table, thus removing the potential conflict of running into removed keys
- A `Lock` property was added to the caches, which the auto-save step uses to indicate to the cache that it shouldn't be flushed by anything else, since it's queued up by itself to be flushed soon.

Thanks again for reporting this issue.
