### ISSUE TITLE
Allow folders

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework#85]
Folders should be allowed within the framework to allow developers to add structure and organization.

Currently, the framework only initializes controllers/services that are direct children of the Controllers and Services folder. With this feature, any descendant could be initialized, as long as it is within a folder (i.e. a module that has another module as a parent will _not_ be initialized--doing so would break existing codebases).

Example:

`Controllers.MyFolder.MyController`:
```lua
function MyController:DoSomething()
   print("Invoked")
end
```

`Controllers.SomeController`:
```lua
function SomeController:Start()
   -- Reference MyController from a folder:
   local myController = self.Controllers.MyFolder.MyController
   myController:DoSomething()
end
```

**Comment by Sleitnick** [comment]
Things to consider:

- This should only work with Folders.
   - ModuleScripts that are children of other ModuleScripts are already being used in the framework & are being explicitly `required` from their parent modules, thus allowing this feature to touch these submodules would break the core codebase, as well as the codebase of other developers.
- Referencing the submodules will be done via dot-notation based on the folder structure.
   - e.g. The module `controllers.MyFolder.AnotherFolder.TestController` would be referenced as `self.Controllers.MyFolder.AnotherFolder.TestController`
- This feature should also include the Modules folders for client, server, and shared.

**Comment by Rocky28447** [comment]
I believe this feature should work with ModuleScripts that are children of other ModuleScripts. AGF does not have forced updates and is only updated if the user wishes for it to be. Therefore, there would be no harm in enabling this feature for things that would break existing codebases as users could take as long as they need to make their game work with the new update.

However, an argument could be made that this should be made to work with existing codebasesbecause AGF lacks proper version control, and therefore a user who updates the framework not knowing it will break their game will have a difficult time reverting to an older version. My response to this would be that because GitHub keeps a record of every change made to every file in every branch of every repository, reverting your AeroServer and AeroClient to the version before this addition would not prove very difficult, though you'd need to know your way around.

**Comment by Reshiram110** [comment]
I definitely would suggest using this feature. My own framework does this, and it has allowed me to organize my game's systems more efficiently.

Here's some reference code that you may find useful:
https://github.com/Reshiram110/Dragon-Engine/blob/master/Shared/Boilerplate.lua

```lua
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- @Name : LoadServicesIn
-- @Description : Loads all services in the given container.
-- @Params : Instance "Container" - The container holding all of the service modules.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
function DragonEngine:LoadServicesIn(Container)
	for _,ServiceModule in pairs(Boilerplate.RecurseFind(Container,"ModuleScript")) do
		if not IsModuleIgnored(ServiceModule) then
			DragonEngine:LoadService(ServiceModule)
		end
	end
end
```

**Comment by KaleidoDeer** [comment]
+1 to this. Its probably my only gripe with the framework.
I don't think it should work with ModuleScripts though. The current trend I see is children of a ModuleScript gets called by the parent. Best case, probably need a settings folder on the server for this.

**Comment by Sleitnick** [comment]
Working branch for folder support: https://github.com/Sleitnick/AeroGameFramework/tree/folders

**Comment by Sleitnick** [comment]
This has been pulled into master.
